name: GroupManager
version: 0.7
main: org.anjocaido.groupmanager.GroupManager
website: http://www.anjocaido.info/
description: Provides on-the-fly system for Permission system created by Nijikokun. But all in memory, and with flat-file saving schedule.
authors:
  - AnjoCaido
  - Gabriel Couto
commands:
  mangroup:
    description: Change player group to one desired.
    usage: /<command> <player> <group>
  addpermission:
    description: Adds a permission to a user.
    usage: /<command> <player> <permissionNode>
  manwhois:
     description: Tell the group that user belongs.
     usage: /<command> <player>
  overload:
    description: Creates a temporary permission copy for that user.
    usage: /<command> <player>
  underload:
    description: Remove the temporary permission copy for player.
    usage: /<command> <player>
  listoverload:
    description: List players in overload-permissions mode made by /overload.
    usage: /<command>
  underloadall:
    description: Remove all overrides made by command /overload.
    usage: /<command>
  mancommit:
    description: Save all permissions on file.
    usage: /<command>
  manreload:
    description: Reload permissions from file.
    usage: /<command>
  listgroups:
    description: List the groups available.
    usage: /<command>
  manpromote:
    description: Promote a player in the same heritage line to a higher rank.
    usage: /<command> <player> <group>
  mandemote:
    description: Demote a player in the same heritage line to a higher rank.
    usage: /<command> <player> <group>