name: GroupManager
version: 0.8
main: org.anjocaido.groupmanager.GroupManager
website: http://www.anjocaido.info/
description: Provides on-the-fly system for Permission system created by Nijikokun. But all in memory, and with flat-file saving schedule.
authors:
  - AnjoCaido
  - Gabriel Couto
commands:
  manuadd:
    description: Change player group to one desired.
    usage: /<command> <player> <group>
  manudel:
    description: Take user to default group. Removes user specific permissions.
    usage: /<command> <player>
  mangadd:
    description: Add group to the system.
    usage: /<command> <group>
  mangdel:
    description: Removes group from the system(all it's users become default)
    usage: /<command> <group>
  manuaddp:
    description: Add permission diretly to the player.
    usage: /<command> <player> <permission>
  manudelp:
    description: Removes permission diretly from the player.
    usage: /<command> <player> <permission>
  manulistp:
    description: List all permissions from a player.
    usage: /<command> <player>
  manucheckp:
    description: Verify if user has a permission, and where it comes from.
    usage: /<command> <player> <permission>
  mangaddp:
    description: Add permission to a group.
    usage: /<command> <group> <permission>
  mangdelp:
    description: Removes permission from a group.
    usage: /<command> <group> <permission>
  manglistp:
    description: Lists all permissions from a group.
    usage: /<command> <group>
  mangcheckp:
    description: Check if group has a permission, and where it comes from.
    usage: /<command> <group> <permission>
  mangaddi:
    description: Add a group to another group inheritance list.
    usage: /<command> <group1> <group2>
  mangdeli:
    description: Remove a group from another group inheritance list.
    usage: /<command> <group1> <group2>
  manwhois:
     description: Tell the group that user belongs.
     usage: /<command> <player>
  tempadd:
    description: Creates a temporary permission copy for that user.
    usage: /<command> <player>
  tempdel:
    description: Remove the temporary permission copy for player.
    usage: /<command> <player>
  templist:
    description: List players in overload-permissions mode made by /tempadd.
    usage: /<command>
  tempdelall:
    description: Remove all overrides made by command /tempadd.
    usage: /<command>
  mansave:
    description: Save all permissions on file.
    usage: /<command>
  manload:
    description: Reload permissions from file.
    usage: /<command>
  listgroups:
    description: List the groups available.
    usage: /<command>
  manpromote:
    description: Promote a player in the same heritage line to a higher rank.
    usage: /<command> <player> <group>
  mandemote:
    description: Demote a player in the same heritage line to a lower rank.
    usage: /<command> <player> <group>
  mantogglevalidate:
    description: Toggle on/off the validating if player is online.
    usage: /<command>